version: '3.8'
services:
  jupyterlab:
    image: nakamura734/geobeginner:latest
    container_name: geobeginner
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - type: bind
        source: C://Docker  # ここをローカルの保存先パスに変更してください
        target: /workspace
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
