version: '3.8'
services:
  jupyterlab:
    image: nakamura734/geobeginner:latest
    ports:
      - "127.0.0.1:8888:8888"  # ローカルホストに限定
    volumes:
      - type: bind
        source: folder path # folder path を書き換えてコンテナのworkspaceフォルダと同期させたい保存先に変更してください
        target: /workspace
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
